[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://www.xn--py-uia.fi/*"
  to = "https://apy.fi/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/gaala"
  to = "https://stream.whappu.fi/"
  status = 302
  force = true