[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "https://www.xn--py-uia.fi/*"
to = "https://apy.fi/:splat"
status = 301
force = true

[[redirects]]
from = "/gaala"
to = "https://youtube.com/live/q-ebaNHZaDo?feature=share"
status = 302
force = true
