[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://www.xn--py-uia.fi/*"
  to = "https://apy.fi/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/gaala"
  to = "https://stream.wappu.fi/"
  status = 301
  force = true

[[redirects]]
  from = "/osta"
  to = "https://osta.apy.fi/"
  status = 301
  force = true